CREATE TABLE CATEGORIA(
  ID INT NOT NULL AUTO INCREMENT,
  NOME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
)

CREATE TABLE USUARIO(
  ID INT NOT NULL AUTO INCREMENT,
  NOME VARCHAR(250) NOT NULL,
  LOGIN VARCHAR(250) NOT NULL,
  SENHA VARCHAR(250) NOT NULL,
  PERFIL_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (PERFIL_ID) 
  REFERENCES PERFIL(ID)
);

CREATE TABLE CONTA(
  ID INT NOT NULL AUTO INCREMENT,
  USUARIO_ID INT NOT NULL,
  PLANO_ID INT NOT NULL,
  CARTAO_ID VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_PLANO_PERFIL FOREIGN KEY (PERFIL_ID) 
  REFERENCES PERFIL(ID)
  CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY (PERFIL_ID) 
  REFERENCES PERFIL(ID)
);

CREATE
